# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-10 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='custumer',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('lat_long', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='delivery_man',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('lat_long', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='menu',
            fields=[
                ('ID', models.IntegerField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
