# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-15 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20160310_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='deliveryMan',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('lat_long', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='delivery_man',
        ),
    ]
